#客户端
server:
  port: 9090
spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/,http://admin:123456@localhost:8762/eureka/
#    register-with-eureka: false
#    fetch-registry: false
  instance:
    appname: eureka.clent.01