#客户端
server:
  port: 9092
spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/,http://admin:123456@localhost:8762/eureka/
#    register-with-eureka: false
#    fetch-registry: false
hystrix:
  metrics:
    enabled: true
# 开启feign客户端hystrix降级处理,新版本默认是关闭的
feign:
  hystrix:
    enabled: true