server:
  port: 8001
spring:
  application:
    name: config-eureka-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yinhaiquan/spring_cloud_config
          search-paths: config
          username: 1083775683@qq.com
          password: yhq123456
      label: master
eureka:
  client:
    service-url:
          defaultZone: http://admin:123456@localhost:8761/eureka/,http://admin:123456@localhost:8762/eureka/
