#注册中心默认端口就是8761，也可通过下面的方式定义其他端口
server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8762/eureka/
    # 由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
    fetch-registry: false
  server:
    enable-self-preservation: false
# 注册中心登录账号密码
security:
  basic:
    enabled: true
  user:
    name: admin
    password: 123456